export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT='REMOVE_COMMENT';
export const COMMENT_FAILED = 'COMMENT_FAILED';

export const ADD_IMAGE = 'ADD_IMAGE';
export const SET_DEFAULT = 'SET_DEFAULT';

export const ACHIEVEMENTS_LOADING = 'ACHIEVEMENTS_LOADING';
export const ACHIEVEMENTS_FAILED = 'ACHIEVEMENTS_FAILED';
export const ADD_ACHIEVEMENTS = 'ADD_ACHIEVEMENTS';

export const THEORIES_LOADING = 'THEORIES_LOADING';
export const THEORIES_FAILED = 'THEORIES_FAILED';
export const ADD_THEORIES = 'ADD_THEORIES';

export const FACTS_LOADING = 'FACTS_LOADING';
export const FACTS_FAILED = 'FACTS_FAILED';
export const ADD_FACTS = 'ADD_FACTS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const FAVOURITE_ACHIEVEMENTS_LOADING = 'FAVORITE_ACHIEVEMENTS_LOADING';
export const FAVOURITES_ACHIEVEMENTS_FAILED = 'FAVORITE_ACHIEVEMENTS_FAILED';
export const ADD_FAVOURITE_ACHIEVEMENTS = 'ADD_FAVORITE_ACHIEVEMENTS';

export const FAVOURITE_FACTS_LOADING = 'FAVORITE_FACTS_LOADING';
export const FAVOURITES_FACTS_FAILED = 'FAVORITE_FACTS_FAILED';
export const ADD_FAVOURITE_FACTS = 'ADD_FAVORITE_FACTS';

export const FAVOURITE_THEORIES_LOADING = 'FAVORITE_THEORIES_LOADING';
export const FAVOURITES_THEORIES_FAILED = 'FAVORITE_THEORIES_FAILED';
export const ADD_FAVOURITE_THEORIES = 'ADD_FAVORITE_THEORIES';

export const ErrorMess = 'ErrorMess';